from emp import bot
import random
import string

music = [
    "https://www.youtube.com/watch?v=w0m0hTrtlWM&t=28s",
    "https://www.youtube.com/watch?v=QK-Z1K67uaA",
    "https://www.youtube.com/watch?v=SUzsih7QJSY",
    "https://www.youtube.com/watch?v=qqK1FrO3BdM",
    "https://www.youtube.com/watch?v=s6WGNd8QR-U",
    "https://www.youtube.com/watch?v=-50cU8DqJzs",
    "https://www.youtube.com/watch?v=F82nyLAAUrk",
    "https://www.youtube.com/watch?v=qqK1FrO3BdM",
    "https://youtu.be/XoJ6TPUG1Tk",
    "https://www.youtube.com/watch?v=AKHSWvmiwP8",
    "https://www.youtube.com/watch?v=c8qrwON1-zE",
    "https://www.youtube.com/watch?v=DJaPakxf2fQ",
    "https://www.youtube.com/watch?v=Qyhbd_5JTJk",
    "https://www.youtube.com/watch?v=Nplz679dsEI",
    "https://www.youtube.com/watch?v=G_ql5IoVcro",
    "https://www.youtube.com/watch?v=GDZPkxBHvzA",
    "https://www.youtube.com/watch?v=jSL1nXza7pM",
    "https://www.youtube.com/watch?v=GHPWLL8EqGw",
    "https://www.youtube.com/watch?v=req-U0G5PCc",
    "https://www.youtube.com/watch?v=8wZTljHP5uA",
    "https://www.youtube.com/watch?v=N4Y81rkT_5o",
    "https://www.youtube.com/watch?v=VrQRPg050gI",
    "https://www.youtube.com/watch?v=rzRqEWJYwX4",
    "https://www.youtube.com/watch?v=GrBgOEMEqyE",
    "https://www.youtube.com/watch?v=zR_477WqAE4",
    "https://www.youtube.com/watch?v=TzLZN1K-PUE",
    "https://www.youtube.com/watch?v=CN-RcplEW5c",
    "https://www.youtube.com/watch?v=SEbxwmjScr8",
    "https://www.youtube.com/watch?v=JW5UEW2kYvc",
    "https://www.youtube.com/watch?v=_PLq0_7k1jk",
    "https://www.youtube.com/watch?v=QJX-nnCjoUM",
    "https://www.youtube.com/watch?v=iG8SmgtoZgM",
    "https://www.youtube.com/watch?v=vlzqfVwUeGY",
    "https://www.youtube.com/watch?v=YVkUvmDQ3HY",
    "https://www.youtube.com/watch?v=5zwq9RCeISY",
    "https://www.youtube.com/watch?v=zUzd9KyIDrM",
    "https://www.youtube.com/watch?v=7kVgb5aPhDQ",
    "https://www.youtube.com/watch?v=PB4J8ntf2EE",
    "https://www.youtube.com/watch?v=G9x0wbKHos0",
    "https://www.youtube.com/watch?v=ccY25Cb3im0",
    "https://www.youtube.com/watch?v=si-ja75bFvI",
    "https://www.youtube.com/watch?v=RMDq-MnpbTo",
    "https://www.youtube.com/watch?v=Soa3gO7tL-c",
    "https://www.youtube.com/watch?v=A1OqtIqzScI",
    "https://www.youtube.com/watch?v=S9PF09URHdQ",
    "https://www.youtube.com/watch?v=6HXa2gVj4mg",
    "https://www.youtube.com/watch?v=ziP2KktJ6Fc",
    "https://www.youtube.com/watch?v=XqmknZNg1yw",
    "https://www.youtube.com/watch?v=nllmm7Q4sj0",
    "https://www.youtube.com/watch?v=JMyzN1SDY0Y",
    "https://www.youtube.com/watch?v=aImYc9AFbOE",
    "https://www.youtube.com/watch?v=dxytyRy-O1k",
    "https://www.youtube.com/watch?v=jnhlldaNp_Y",
    "https://www.youtube.com/watch?v=7oVefMrL7WM",
    "https://www.youtube.com/watch?v=rK0CR3kUEsA",
    "https://www.youtube.com/watch?v=9Ht5RZpzPqw",
    "https://www.youtube.com/watch?v=4fndeDfaWCg",
    "https://www.youtube.com/watch?v=d5aPlTZA9iA",
    "https://www.youtube.com/watch?v=6Dh-RL__uN4",
    "https://www.youtube.com/watch?v=rm9coqlk8fY",
    "https://www.youtube.com/watch?v=kXYiU_JCYtU",
    "https://www.youtube.com/watch?v=XbGs_qK2PQA",
    "https://www.youtube.com/watch?v=fJbALcAlijg",
    "https://www.youtube.com/watch?v=fHjMpT-K8u0",
    "https://www.youtube.com/watch?v=dhYOPzcsbGM",
    "https://www.youtube.com/watch?v=T1q9Ub7y52g",
    "https://www.youtube.com/watch?v=k7WRH5TN4Jk",
    "https://www.youtube.com/watch?v=Zo51mCz4y1I",
    "https://www.youtube.com/watch?v=6Dh-RL__uN4"
]

@bot.message_handler(commands = ["randommusic"])
def randommusic(message):
    target = random.choice(music)
    bot.send_message(message.chat.id, target)
